server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_app_users
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import: "optional:configserver:http://localhost:8888"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakerevents
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      notificationBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        sliding-window-size: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
  retry:
    instances:
      notificationRetry:
        max-attempts: 3
        wait-duration: 500ms
      retry-exceptions:
          - java.io.IOException
          - feign.FeignException
  ratelimiter:
    instances:
      notificationRateLimiter:
        limitForPeriod: 5      # max 5 calls
        limitRefreshPeriod: 10s # refresh every 10 seconds
        timeoutDuration: 0     # do not wait, fail immediately if limit exceeded